package modelo;
// Generated 23/05/2014 11:00:58 by Hibernate Tools 3.6.0



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private String nome;
     private String telefone;
     private String endereco;

    public Cliente() {
    }

    public Cliente(int id, String nome, String telefone, String endereco) {
       this.id = id;
       this.nome = nome;
       this.telefone = telefone;
       this.endereco = endereco;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }




}


